### ISSUE TITLE
Zotac Domain Change; scripts have stopped working

### ISSUE THREAD

**Issue by ColdShills** [krowve/zotacscripts#2]
Hello,
I had these scripts up and running like a dream, but a few days ago Zotac switched their domain back from us.zotacstore.com to zotacstore.com/us. (us.zotacstore.com works again now but it just redirects you to zotacstore.com/us). The scripts have totally stopped working for me since the domain change. I'm smart & techy but not a coder... please help me get the scripts working again!
Thank you so much in advance for any of your time! <3

**Comment by ColdShills** [comment]
Also I know the queue makes the scripts seem like they aren't worth having anymore but they definitely still are! You can cart & checkout faster than everyone who is in the store at the same time as you! I barely snagged a white 3070 via the queue about 3 weeks ago, and I only got it because I had the scripts running despite going through the queue! Falcodrin announced that model as out of stock literally within 30 seconds of me checking out! Also I wouldn't be shocked if they randomly stopped doing the queue again & started doing random drops just to keep us on our toes... God knows they aren't consistent. lol

**Comment by ColdShills** [comment]
I fixed it =) My first time ever using Github too! If the scripts stopped working for you switch to my fork of the scripts! Once @krowve returns I'm sure he'll update them!

**Comment by krowve** [comment]
Thanks for the update, this is now merged.
